[package]
name = "hwi_rs"
version = "0.1.0"
edition = "2021"


[dependencies]
iced = {version = "0.10.0", features = ["tokio", "wgpu"]}
lazy_static = "1.4.0"
nvml-wrapper = "0.9.0"
reqwest = "0.11.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
