[package]
name = "hwi_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvml-wrapper = "0.9.0"
raw-cpuid = "10.6.1"
systemstat = "0.2.3"
cpuid = "0.1.1"

egui = "0.20.1"
eframe = "0.20.1"
